### ISSUE TITLE
关于如何使用clash dashboard

### ISSUE THREAD

**Issue by Tangent-H** [VocabVictor/clash-for-AutoDL#1]
你好！谢谢你的这个仓库，我成功在autodl服务器上开启了我的clash代理

不过clash dashboard我不是很清楚应该怎么使用，在我执行了`sudo bash start.sh`后，我的输出结果是:

```
CPU architecture: amd64

正在检测订阅地址...
Clash订阅地址可访问！                                      [  OK  ]

正在下载Clash配置文件...
配置文件config.yaml下载成功！                              [  OK  ]

判断订阅内容是否符合clash配置文件标准:
解码后的内容不符合clash标准，尝试将其转换为标准格式
配置文件已成功转换成clash标准格式

正在启动Clash服务...
服务启动成功！                                             [  OK  ]

Clash Dashboard 访问地址: http://<ip>:9090/ui
Secret: <这里我隐去了>

请执行以下命令加载环境变量: source /etc/profile.d/clash.sh

请执行以下命令开启系统代理: proxy_on

若要临时关闭系统代理，请执行: proxy_off
```

上面的clash dashboard访问地址中显示的<ip>并不是一个具体的ip地址，显示的就是**\<ip\>**，请问我应该如何去访问clash dashboard?

另外，之前有咨询过autodl的客服，在容器中使用代理有下次无法ssh连接的风险，这个是真的吗？（为了避免这种事情发生，我会将clash完全关掉再关机，不过不清楚不关的话会发生什么

谢谢！

**Comment by Tangent-H** [comment]
第一个问题已解决

解决方案是：使用ssh将服务器上external-controller的端口转发到本地的端口，然后访问https://yacd.haishan.me/输入的API Based URL是http://127.0.0.1:<映射到的本地端口>即可正常使用yacd

```
ssh -p <ssh端口> -L <external-controller端口>:127.0.0.1:<将要转发到的本地端口> root@xxxx.com
```

**Comment by VocabVictor** [comment]
抱歉同学现在才看到，我已经更新了图文说明了

**Comment by VocabVictor** [comment]
在容器中使用代理有下次无法ssh连接的风险，这个是真的吗？和其他能够代理到更底层网络的梯子不同，clash的只是对应用层的代理，应该是不会影响到SSH的连接的

**Comment by VocabVictor** [comment]
你的考虑我也会着手解决，后面我会加上在关机的时候自动关闭clash的代码
