### ISSUE TITLE
source ./start.sh 失败

### ISSUE THREAD

**Issue by NyKxo1** [VocabVictor/clash-for-AutoDL#11]
正在检测订阅地址...
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
Clash订阅地址不可访问！                                    [FAILED]
成功创建logs目录: /root/autodl-tmp/clash-for-AutoDL/logs
root@autodl-container-d4e347a000-1fc95dae:~/autodl-tmp/clash-for-AutoDL# 
![1](https://github.com/user-attachments/assets/0f98c301-fb5c-4735-937a-ba377b848cc3)

**Comment by VocabVictor** [comment]
同学，这是因为你这个订阅地址要开梯子才能访问的

**Comment by VocabVictor** [comment]
你可以直接吧配置文件保存到conf文件夹下

**Comment by 2221867603w** [comment]
![image](https://github.com/user-attachments/assets/399662ab-e8ac-47e1-bd9e-00b612482ba5)
大佬，我把配置文件上传到conf目录下，还是报错Clash订阅地址不可访问！
