### ISSUE TITLE
ping不通

### ISSUE THREAD

**Issue by HuzhenYou** [VocabVictor/clash-for-AutoDL#12]
<img width="864" alt="image" src="https://github.com/user-attachments/assets/3e9cc4e7-d929-42d8-bb3c-89deec75ec45">
运行成功，但`lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'`没反应，ping 也不通呢

**Comment by VocabVictor** [comment]
lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]' 没反应，这是Clash 核心进程没有正常启动，我会尝试修复这个bug，ping是不可能通的，详情请看README中的解释。

**Comment by HuzhenYou** [comment]
好的，感谢回复～

**Comment by WSBG** [comment]
> lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]' 没反应，这是Clash 核心进程没有正常启动，我会尝试修复这个bug，ping是不可能通的，详情请看README中的解释。

请问我现在还是遇到 lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]' 没反应的问题是怎么回事

**Comment by VocabVictor** [comment]
请检查conf/config.yaml是否是正常的，我发现大部分clash核心进程异常启动都是这个原因，很多clash-for-linux项目都是考虑引入第三方的修复程序自动修复这个错误，但是这个的引入会导致仓库文件大小显著增大，你可以手动去把配置信息粘贴进去，再次启动即可正常。

**Comment by WSBG** [comment]
> 请检查conf/config.yaml是否是正常的，我发现大部分clash核心进程异常启动都是这个原因，很多clash-for-linux项目都是考虑引入第三方的修复程序自动修复这个错误，但是这个的引入会导致仓库文件大小显著增大，你可以手动去把配置信息粘贴进去，再次启动即可正常。

 谢谢,问题出在我的订阅链接不挂梯子是下不下来的,然后我也疏忽了,没发现它根本就没下下来)

**Comment by WSChange** [comment]
> 请检查conf/config.yaml是否是正常的，我发现大部分clash核心进程异常启动都是这个原因，很多clash-for-linux项目都是考虑引入第三方的修复程序自动修复这个错误，但是这个的引入会导致仓库文件大小显著增大，你可以手动去把配置信息粘贴进去，再次启动即可正常。

请问配置信息在哪里看

**Comment by HuzhenYou** [comment]
> > 请检查conf/config.yaml是否是正常的，我发现大部分clash核心进程异常启动都是这个原因，很多clash-for-linux项目都是考虑引入第三方的修复程序自动修复这个错误，但是这个的引入会导致仓库文件大小显著增大，你可以手动去把配置信息粘贴进去，再次启动即可正常。
> 
> 请问配置信息在哪里看

<img width="843" alt="image" src="https://github.com/user-attachments/assets/2c9c78d1-1d63-4a8f-abc0-caad5f428a23">
