### ISSUE TITLE
订阅失败

### ISSUE THREAD

**Issue by immrzhf** [VocabVictor/clash-for-AutoDL#13]
你好，能看下这是啥问题吗，订阅失败了，提示链接不可访问，logs文件夹是空的，但是我用clash for windows 是可以订阅的
![image](https://github.com/user-attachments/assets/6e09fe34-728d-4a30-8ece-e3f3804077fd)

**Comment by VocabVictor** [comment]
其实这个就是有些链接只能开了梯子才能正常访问，个人目前档期抽不开，同学你可以考虑在conf文件夹下，将clash for windows下载得到的config复制过来保存为config.yaml即可

**Comment by VocabVictor** [comment]
这个解决方案要等我有空了再更新

**Comment by ShawnLee0910** [comment]
你好，请问config.yaml要放在那个目录下

**Comment by ShawnLee0910** [comment]
> 这个解决方案要等我有空了再更新



> 这个解决方案要等我有空了再更新

你好，请问config.yaml要放在那个目录下
