### ISSUE TITLE
新的shell不要自动开启怎么设置

### ISSUE THREAD

**Issue by IgnoranceSmile** [VocabVictor/clash-for-AutoDL#14]
“打开一个新的shell，都会自动启动Clash”
请问怎么设置关闭这一功能呢

**Comment by VocabVictor** [comment]
目前没有设置，但是你可以去.bashrc文件里面去删除proxy_on 这一行

**Comment by VocabVictor** [comment]
我会择期添加上这个功能的，感谢支持

**Comment by VocabVictor** [comment]
而且自动启动clash，其实是指会自动添加代理相关的环境变量，只有检测到clash进程不存在的时候才会自动申请进程实例，因此不必担心内存占用问题
