### ISSUE TITLE
请问这个项目是如何选择节点的呢，导入了url之后好像并没有节点的选择

### ISSUE THREAD

**Issue by a1e-the** [VocabVictor/clash-for-AutoDL#15]

**Comment by VocabVictor** [comment]
这个功能倒是没有考虑到，因为这个项目初衷只是本人开发来给自己用的，我会择期添加上这个功能的

**Comment by a1e-the** [comment]
谢谢回复，那这个是自己随机选择的可用节点嘛，source ./start.sh这一步我显示成功开启了代理。但是lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'这一步却是输出了空内容嘞。
&nbsp;


pace
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月27日(星期六) 中午1:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [VocabVictor/clash-for-AutoDL] 请问这个项目是如何选择节点的呢，导入了url之后好像并没有节点的选择 (Issue #15)














 
这个功能倒是没有考虑到，因为这个项目初衷只是本人开发来给自己用的，我会择期添加上这个功能的

**Comment by VocabVictor** [comment]
那这个是自己随机选择的可用节点嘛，对的，这也是config,yaml 里面的选项

**Comment by VocabVictor** [comment]
> lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'这一步却是输出了空内容嘞。

完犊子，说明没有clash没有成功

**Comment by VocabVictor** [comment]
前面几个issue也有类似的情况，如[#13](https://github.com/VocabVictor/clash-for-AutoDL/issues/13)，这些都是订阅链接虽热下载的时候成功返回状态码200，但是打开conf/config.yaml 查看却是乱码或不符合标准格式，因此clash进程不能成功启动。

**Comment by VocabVictor** [comment]
选择节点，当前大家的方案是使用Clash Dashboard，在网页端切换，操作比较简单，而且dash项目维护时间比较久，网上资料齐全，可以在我功能排期还没到的时候，暂时使用这个方案，关于如何部署Clash Dashboard，在项目首页的教程里面有。
