### ISSUE TITLE
ping不通

### ISSUE THREAD

**Issue by fffllllxxxxxxxx** [VocabVictor/clash-for-AutoDL#17]
<img width="732" alt="image" src="https://github.com/user-attachments/assets/32936c61-3f8f-4273-acd9-7087c4b778d9">
<img width="907" alt="image" src="https://github.com/user-attachments/assets/97355d4d-250b-4ff9-beca-003269b9e858">

但还是ping不通，想从github上下载 失败

**Comment by VocabVictor** [comment]
同学你这个已经是成功启动了

**Comment by VocabVictor** [comment]
Ping使用的是 ICMP（Internet Control Message Protocol） 协议，是网络层协议，Clash 只会代理传输层的TCP和UDP流量，因此无论clash是否能够正常工作，ping google.com 都是不会有效果的。

**Comment by VocabVictor** [comment]
应该使用`curl -i google.com`测试

**Comment by DingYX0731** [comment]
@fffllllxxxxxxxx 请问你现在可以正常使用吗？虽然成功启动，但有时候不代表可以正常使用，问题可能出现在哪呢？
![QQ_1723693138911](https://github.com/user-attachments/assets/c1629909-f30b-4ddd-8692-68ccbc430504)

**Comment by DingYX0731** [comment]
上述问题已解决，config设置的内容我写在了 [#12 ](https://github.com/VocabVictor/clash-for-AutoDL/issues/12) 中

**Comment by Florentino17** [comment]
> 上述问题已解决，config设置的内容在 [#12 ](https://github.com/VocabVictor/clash-for-AutoDL/issues/12) 中

你好，想问问是什么原因，我也是lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'的输出正常，但是curl失败502
