### ISSUE TITLE
查看服务器端口有问题

### ISSUE THREAD

**Issue by arrowonstr** [VocabVictor/clash-for-AutoDL#18]
其他都正常，服务器端口不显示
![image](https://github.com/user-attachments/assets/95a5029a-2557-410a-a283-f2b46f15ba7f)
google也无法访问
![image](https://github.com/user-attachments/assets/8464d126-894a-4d68-9711-42c237d90f28)

**Comment by VocabVictor** [comment]
> 请检查conf/config.yaml是否是正常的，我发现大部分clash核心进程异常启动都是这个原因，很多clash-for-linux项目都是考虑引入第三方的修复程序自动修复这个错误，但是这个的引入会导致仓库文件大小显著增大，你可以手动去把配置信息粘贴进去，再次启动即可正常。

**Comment by VocabVictor** [comment]
[#12](https://github.com/VocabVictor/clash-for-AutoDL/issues/12)
