### ISSUE TITLE
执行代码出现错误，什么情况

### ISSUE THREAD

**Issue by LeviArckman** [VocabVictor/clash-for-AutoDL#19]
![image](https://github.com/user-attachments/assets/8dacb62a-1ec5-4f11-a72f-a29902098bfa)

**Comment by LeviArckman** [comment]
> ![image](https://private-user-images.githubusercontent.com/39213438/357393560-8dacb62a-1ec5-4f11-a72f-a29902098bfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTA0NTYsIm5iZiI6MTcyMzU1MDE1NiwicGF0aCI6Ii8zOTIxMzQzOC8zNTczOTM1NjAtOGRhY2I2MmEtMWVjNS00ZjExLWE3MmYtYTI5OTAyMDk4YmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDExNTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0Zjk5YjY3MzZkNGQwMjA3ZTdlODMzZmIxNDQzODhmYTFhOTU3MmMxNGY4ZTQ5MTcyODNiMDU0ZTdkZDFlZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GDjDUtcmgmq95qKNFXXffKghyYtla4-31J6Sq1sn-Io)

![image](https://github.com/user-attachments/assets/3c36ca5e-13f7-4056-91c5-2babc6183c53)

**Comment by VocabVictor** [comment]
lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'，请先用该命令查询 clash 是否正常启动，如果正常启动了，网页请求相关代码依然报错，麻烦在该 issue 上反映

**Comment by LeviArckman** [comment]
> lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'，请先用该命令查询 clash 是否正常启动，如果正常启动了，网页请求相关代码依然报错，麻烦在该 issue 上反映

![image](https://github.com/user-attachments/assets/6a42b313-6a50-4fd4-8ec2-7917a5f26772)
我输入该代码，没有出现什么东西

**Comment by DingYX0731** [comment]
+1 我也是，请问解决了嘛？

**Comment by VocabVictor** [comment]
请检查conf/config.yaml是否是正常的，我发现大部分clash核心进程异常启动都是这个原因，很多clash-for-linux项目都是考虑引入第三方的修复程序自动修复这个错误，但是这个的引入会导致仓库文件大小显著增大，你可以手动去把配置信息粘贴进去，再次启动即可正常。

**Comment by DingYX0731** [comment]
怎么样判断conf/config.yaml是否正常？去哪里参照配置信息？一般需要改下面的哪些config呢？谢谢
![QQ_1723651340989](https://github.com/user-attachments/assets/b1c3feea-8fbe-49c4-a352-09321e7d1ebd)

**Comment by VocabVictor** [comment]
要符合yaml的格式，这个显然是错误的

**Comment by VocabVictor** [comment]
这个问题属于月经问题了，可以参考其他issue里面的方法解决

**Comment by DingYX0731** [comment]
谢谢。我修改了yaml文件：

现在输入 `lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'` 可以正常运行，但是在测试google的时候还是出现了问题，是我自身节点的问题嘛？
![QQ_1723690937788](https://github.com/user-attachments/assets/391fe1cc-c492-45e8-b3dc-01c3d76e0306)
