### ISSUE TITLE
我用6006可以打开web但是输入一直有误……

### ISSUE THREAD

**Issue by Bald0Wang** [VocabVictor/clash-for-AutoDL#2]
![image](https://github.com/VocabVictor/clash-for-AutoDL/assets/38057320/7dec9b5f-bdd4-4eb4-9ada-ff6699718909)
这个是哪里出问题了呢，，

**Comment by VocabVictor** [comment]
看样子应该是IP输入错误了，应该输入的是服务器的IP或者域名地址
