### ISSUE TITLE
下载github或hugging face上的文件一直报错

### ISSUE THREAD

**Issue by LeviArckman** [VocabVictor/clash-for-AutoDL#20]
![b583c0cd04e9bbd110f0a17a44145a1](https://github.com/user-attachments/assets/5cea469d-ad94-40f4-b208-bc7744e3a8a4)

**Comment by zhangxue0** [comment]
> 麻烦重新敲一下`lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'`，看不太清楚，从目前的输出看应该是没有启动成功

为什么我敲这个没有返回任何东西
