### ISSUE TITLE
使用XFX的节点URLhttps://66cd4a.xfxcloud.click/api/v1/client/subscribe?token=xxx（这里保密），启动失败

### ISSUE THREAD

**Issue by ErwinZhou** [VocabVictor/clash-for-AutoDL#21]
(base) root@autodl-container-93544080dd-27d7c593:~/autodl-tmp/clash-for-AutoDL# source ./start.sh
配置文件已存在，无需下载。
成功创建logs目录: /root/autodl-tmp/clash-for-AutoDL/logs

正在启动Clash服务...
服务启动成功！                                             [  OK  ]

Clash Dashboard 访问地址: http://<ip>:6006/ui
Secret: 【这里保密了就】

已添加代理函数到 .bashrc，并设置为自动执行。\n
请执行以下命令启动系统代理: proxy_on

若要临时关闭系统代理，请执行: proxy_off

若需要彻底删除，请调用: shutdown_system

+--------------------------------------------------AutoDL--------------------------------------------------------+
目录说明:
╔═════════════════╦════════╦════╦═════════════════════════════════════════════════════════════════════════╗
║目录             ║名称    ║速度║说明                                                                     ║
╠═════════════════╬════════╬════╬═════════════════════════════════════════════════════════════════════════╣
║/                ║系 统 盘║一般║实例关机数据不会丢失，可存放代码等。会随保存镜像一起保存。               ║
║/root/autodl-tmp ║数 据 盘║ 快 ║实例关机数据不会丢失，可存放读写IO要求高的数据。但不会随保存镜像一起保存 ║
╚═════════════════╩════════╩════╩═════════════════════════════════════════════════════════════════════════╝
CPU ：16 核心
内存：120 GB
GPU ：NVIDIA GeForce RTX 4090, 1
存储：
  系 统 盘/               ：41% 13G/30G
  数 据 盘/root/autodl-tmp：73% 402G/550G
+----------------------------------------------------------------------------------------------------------------+
*注意: 
1.系统盘较小请将大的数据存放于数据盘或网盘中，重置系统时数据盘和网盘中的数据不受影响
2.清理系统盘请参考：https://www.autodl.com/docs/qa/
服务关闭成功！ [  OK  ]

服务启动成功！ [  OK  ]

[×] 尝试重启后，clash 进程未能启动。代理启动失败

**Comment by VocabVictor** [comment]
log里面会有不能启动的具体原因，方便的话请把`/root/autodl-tmp/clash-for-AutoDL/logs`的内容展示一下

**Comment by ErwinZhou** [comment]
没关系我已解决，感谢
