### ISSUE TITLE
代理开启后，查看监听端口，显示为空

### ISSUE THREAD

**Issue by zhangzhefang-github** [VocabVictor/clash-for-AutoDL#23]
lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'
![image](https://github.com/user-attachments/assets/92de7d89-a2f6-495c-a162-4c684b1e6ba4)

**Comment by VocabVictor** [comment]
有些同学想要自己启动，不想要自动启动，所以我把自动开启取消了，可以自行运行proxy_on

**Comment by VocabVictor** [comment]
同学麻烦再看一下，应该修复好了

**Comment by jiannghx** [comment]
我也有一样的问题

**Comment by VocabVictor** [comment]
能打开logs/clash.log文件，给我看看里面的内容吗

**Comment by jiannghx** [comment]
> 能打开logs/clash.log文件，给我看看里面的内容吗
![image](https://github.com/user-attachments/assets/adc7629b-a16c-45bf-a38b-04414fc218a3)
不好意思看错了，我的问题是这样的

**Comment by VocabVictor** [comment]
![image](https://github.com/user-attachments/assets/1d58fc6a-39ed-4f52-a184-c03b754ebb12)
现在这个新版本应该不会了

**Comment by zhangzhefang-github** [comment]
thanks
