### ISSUE TITLE
报错如下：bash: proxy_on: command not found（附图）

### ISSUE THREAD

**Issue by ruuioche** [VocabVictor/clash-for-AutoDL#25]
![报错](https://github.com/user-attachments/assets/1b464d55-29da-4458-a9a1-6164ad31a7bf)

**Comment by ruuioche** [comment]
已通过其他方式解决

**Comment by LLlovecat** [comment]
> 已通过其他方式解决

怎么解决的哥

**Comment by SH31415** [comment]
envsubst没有下载，https://gitcode.com/gh_mirrors/en/envsubst/overview?utm_source=artical_gitcode&index=bottom&type=card&webUrl&isLogin=1官网下载好，就可以了

**Comment by yinyuanzhang** [comment]
请问如何解决的啊

**Comment by xjxinchina** [comment]
> 请问如何解决的啊

我使用SH13415那个哥们的方法envsubst没有下载，https://gitcode.com/gh_mirrors/en/envsubst/overview?utm_source=artical_gitcode&index=bottom&type=card&webUrl&isLogin=1，在这里下载，然后sudo apt-get update
，sudo apt-get install gettext有参考别的哥们的东西执行了这两条。之后重新执行以下官方教程里的source ./start.sh就可以了。
