### ISSUE TITLE
服务成功打开，但是https_proxy=http://127.0.0.1:，后面的端口号为空

### ISSUE THREAD

**Issue by 404known** [VocabVictor/clash-for-AutoDL#26]
lsof -i -P -n | grep LISTEN | grep -E ':6006|:789[0-9]'
clash-lin 1263 root    3u  IPv6 585189040      0t0  TCP *:7890 (LISTEN)
clash-lin 1263 root    8u  IPv6 585189042      0t0  TCP *:7891 (LISTEN)
clash-lin 1263 root   10u  IPv6 585189044      0t0  TCP *:7892 (LISTEN)
但是
env | grep -E 'http_proxy|https_proxy'
https_proxy=http://127.0.0.1:
http_proxy=http://127.0.0.1:

并且curl https://scholar.google.com.hk/
curl: (7) Failed to connect to 127.0.0.1 port 1080 after 0 ms: Connection refused

**Comment by VocabVictor** [comment]
同学麻烦再看一下，应该修复好了
