### ISSUE TITLE
请问 https_proxy 和 http_proxy 后的端口为空怎么处理呀

### ISSUE THREAD

**Issue by mymichaelmy** [VocabVictor/clash-for-AutoDL#27]
目前根据说明配置完并启动之后，显示是这样的，然后也连不上 google，不知道应该怎么处理了
<img width="917" alt="Screen Shot 2024-10-03 at 16 39 21" src="https://github.com/user-attachments/assets/01c4e9a7-ece6-45da-8da5-8197772e48d5">

**Comment by VocabVictor** [comment]
请重新拉取最新的github项目再试一下，这个可能是还没更新的老版

**Comment by VocabVictor** [comment]
我明白了，应该是你的订阅链接有些特殊，用的是mixed-port，容我修改一下

**Comment by mymichaelmy** [comment]
> 现在这个问题已经解决，关闭该问题。

现在确实可以了，非常感谢 @VocabVictor
