### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

### ISSUE THREAD

**Issue by 1859140** [VocabVictor/clash-for-AutoDL#3]
代理挂上去了，也成功开启了
但是下数据集的时候返回了urllib.error.HTTPError: HTTP Error 502: Bad Gateway
是谷歌的数据集FaceForensics，是不是访问网址的时候还是被墙住了啊

**Comment by 1859140** [comment]
不知道有没有人需要但是解决了--server 选择EU2就可以了

**Comment by VocabVictor** [comment]
同学你好，请问你方便能提供一个最小示例帮助我复现你这个bug嘛，谢谢

**Comment by 1859140** [comment]
非常感谢您的帮助，我在网络上找到了解决办法，已经成功解决了。原因是选择运行数据集下载代码的时候，选择参数Server的时候选了欧洲源所以bad gateway了。后面我换了Server中别的选项就下载成功了，所以猜测应该是数据集网站的问题（因为我挂不挂梯子都会报出bad gateway的问题）。
再次感谢您！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月03日 23:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [VocabVictor/clash-for-AutoDL] urllib.error.HTTPError: HTTP Error 502: Bad Gateway (Issue #3) |

同学你好，请问你方便能提供一个最小示例帮助我复现你这个bug嘛，谢谢
