### ISSUE TITLE
开启代理（似乎）成功，但访问Clash Dashboard时“404 page not found”

### ISSUE THREAD

**Issue by zza234s** [VocabVictor/clash-for-AutoDL#30]
首先非常感谢作者的开源该项目。
我在按照readme文件的教程，尝试打开管理界面时遇到了“404 not found”的问题：

**加上“/ui”后出现404 not found**
![image](https://github.com/user-attachments/assets/30560e2d-4e79-4bf4-ab93-dad144df2e47)

**如果地址不加“ui”则出现 {"hello":"mihomo"}**
![image](https://github.com/user-attachments/assets/787f691c-7854-42f4-bdae-440a13306738)

**服务器端的提示**
![image](https://github.com/user-attachments/assets/3d42ad0b-0df6-4ac5-8500-2423b67008a3)

**运行wget 127.0.0.1:6006/ui也会返回Not Found**：
![image](https://github.com/user-attachments/assets/38203237-ee68-4123-bce0-50a06816d142)

**Comment by VocabVictor** [comment]
因为原始的clash项目作者已经删库了，这是一个叫mihomo的拷贝版本，我预计下周把这个bug修复，等不及的同学可以直接把bin里面的换成原始的clash core，应该就可以解决问题。

**Comment by zza234s** [comment]
> 因为原始的clash项目作者已经删库了，这是一个叫mihomo的拷贝版本，我预计下周把这个bug修复，等不及的同学可以直接把bin里面的换成原始的clash core，应该就可以解决问题。

伟大无需多言！感谢您

**Comment by hututututu209** [comment]
> > 因为原始的clash项目作者已经删库了，这是一个叫mihomo的拷贝版本，我预计下周把这个bug修复，等不及的同学可以直接把bin里面的换成原始的clash core，应该就可以解决问题。
> 
> 伟大无需多言！感谢您

请问下是把bin里的文件换成啥呀？

**Comment by xy3xy3** [comment]
@VocabVictor 似乎没有修复,我2025 1 24使用还是/ui 404

**Comment by Wznnnnn** [comment]
same question
