### ISSUE TITLE
SSL验证失败

### ISSUE THREAD

**Issue by WHKLV** [VocabVictor/clash-for-AutoDL#31]
(base) root@autodl-container-9403468337-4722c544:~/clash-for-AutoDL# source ./start.sh
正在下载 subconverter... (尝试 1/3)
下载失败。错误代码: 5
SSL验证失败。
重试中...
正在下载 subconverter... (尝试 2/3)
下载失败。错误代码: 5
SSL验证失败。
重试中...
正在下载 subconverter... (尝试 3/3)
下载失败。错误代码: 5
SSL验证失败。
重试中...
安装 subconverter 失败，请检查网络连接或手动安装。

**Comment by VocabVictor** [comment]
稍等，我明天修改一下，也可以手动把start.sh里面的kkgithub换掉，换成任意的国内github代理

**Comment by VocabVictor** [comment]
kgithub用的人太多了，日常抽风
