### ISSUE TITLE
URL订阅地址格式是什么呀，我的url不是一个yml文件，会下载配置文件失败

### ISSUE THREAD

**Issue by Heimdall-Nss** [VocabVictor/clash-for-AutoDL#36]
已搜索issues。
报错：
```shell
正在检测订阅地址...
Clash订阅地址可访问！

正在下载Clash配置文件...
配置文件下载成功！
错误：文件不包含冒号，可能不是有效的YAML
检测到配置文件格式不正确，尝试使用subconverter进行转换...
Subconverter转换成功，文件现在是有效的YAML格式
```
查看发现config.yaml是空的，因为.env中的url格式类似于  https://xxx.com/api/v1/client/subscribe?token=xxxxxxxxxxxxxxxxxxxxxxxxx
并不是一个config文件。这是我节点订阅的问题吗，应该怎么解决呢

**Comment by VocabVictor** [comment]
可以直接粘贴订阅文件内容到conf/config.yaml里面

**Comment by VocabVictor** [comment]
也有那种订阅转换网站，可以把你这个第三方订阅转换成标准订阅

**Comment by xxxxxxxmmmmm** [comment]
想问下解决了吗，我也是类似格式的链接，yaml文件不是空的但是检测失败

<img width="1073" height="436" alt="Image" src="https://github.com/user-attachments/assets/881d5e18-203b-420c-8a0a-ffff7340998e" />

**Comment by liuhui0426** [comment]
上面楼，我也遇到你的问题了，你解决了吗
