### ISSUE TITLE
不用费这个劲了，现在autoDL自带翻墙了

### ISSUE THREAD

**Issue by shuishen49** [VocabVictor/clash-for-AutoDL#4]
加速
source /etc/network_turbo
取消加速
unset http_proxy && unset https_proxy

执行这个命令就可以翻墙了。

**Comment by handicaps** [comment]
没有用啊，我想在meta官网下载llama3，但是这个用国内的网就会403 forbidden。用你这里提供的命令执行后也没法解决这个问题。

**Comment by lufengjun618** [comment]
扯淡，确实不行

**Comment by VocabVictor** [comment]
用梯子下大模型主要是流量消耗太大了，可以考虑使用国内的huggingface镜像，参考链接如下：[](https://hf-mirror.com/)
