### ISSUE TITLE
bash: proxy_on: command not found

### ISSUE THREAD

**Issue by lufengjun618** [VocabVictor/clash-for-AutoDL#5]
奇怪的提示：
(base) root@autodl-container-9403468337-b429962d:~/clash-for-AutoDL# proxy_on
bash: proxy_on: command not found

**Comment by VocabVictor** [comment]
执行结束以后要在新的shell才能使用proxy_on，我已经修复了这个bug，并且以后打开新的shell就会自动启动梯子，不需要每次使用proxy_on了
