### ISSUE TITLE
clash 进程已存在，代理已开启，但是无法访问huggingface和github

### ISSUE THREAD

**Issue by ropz12138** [VocabVictor/clash-for-AutoDL#8]
# 当前错误信息
2.清理系统盘请参考：https://www.autodl.com/docs/qa/
[√] clash 进程已存在，代理已开启
(base) root@autodl-container-a899408bbc-d018641c:~/autodl-tmp# git clone https://huggingface.co/moka-ai/m3e-base
Cloning into 'm3e-base'...
fatal: unable to access 'https://huggingface.co/moka-ai/m3e-base/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
(base) root@autodl-container-a899408bbc-d018641c:~/autodl-tmp# git clone https://github.com/casper-hansen/AutoAWQ.git
Cloning into 'AutoAWQ'...
fatal: unable to access 'https://github.com/casper-hansen/AutoAWQ.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
(base) root@autodl-container-a899408bbc-d018641c:~/autodl-tmp# 

# 前期操作
## 第一次运行报错
(base) root@autodl-container-a899408bbc-d018641c:~/autodl-tmp/clash-for-AutoDL# source ./start.sh

正在检测订阅地址...
Clash订阅地址可访问！                                      [  OK  ]

正在下载Clash配置文件...
配置文件config.yaml下载成功！                              [  OK  ]
日志文件 logs/clash.log 已创建。

正在启动Clash服务...
服务启动成功！                                             [  OK  ]

Clash Dashboard 访问地址: http://<ip>:6006/ui
Secret: e9af2a3cd6f6d8d14ef169cb1c35808a9078c3d67cc290cdcf48fd1abfd6c43b

已添加代理函数到 .bashrc，并设置为自动执行。\n
请执行以下命令启动系统代理: proxy_on

若要临时关闭系统代理，请执行: proxy_off

若需要彻底删除，请调用: shutdown_system

2.清理系统盘请参考：https://www.autodl.com/docs/qa/
服务关闭成功！                                             [  OK  ]
服务启动成功！                                             [  OK  ]
[×] 尝试重启后，clash 进程未能启动。代理启动失败

## 解决办法
我在clash.log里看到：time="2024-07-03T16:24:11+08:00" level=fatal msg="Parse config error: yaml: unmarshal errors:\n  line 1097: cannot unmarshal !!map into string"
我将第1097行从：
- MATCH,Othersexternal-ui: /root/autodl-tmp/clash-for-AutoDL/dashboard/public
改成：
external-ui: /root/autodl-tmp/clash-for-AutoDL/dashboard/public

## 情况
关掉clash后再运行：[√] clash 进程已存在，代理已开启
当下的clash.log：time="2024-07-03T16:26:32+08:00" level=info msg="Start initial compatible provider Proxy"
time="2024-07-03T16:26:32+08:00" level=info msg="Start initial compatible provider Domestic"
time="2024-07-03T16:26:32+08:00" level=info msg="Start initial compatible provider Others"
time="2024-07-03T16:26:32+08:00" level=info msg="Start initial compatible provider GlobalTV"
time="2024-07-03T16:26:32+08:00" level=info msg="Start initial compatible provider AsianTV"
time="2024-07-03T16:26:32+08:00" level=info msg="RESTful API listening at: 127.0.0.1:6006"
访问外网情况：
(base) root@autodl-container-a899408bbc-d018641c:~/autodl-tmp# export http_proxy="http://127.0.0.1:7890"
export https_proxy="http://127.0.0.1:7890"
(base) root@autodl-container-a899408bbc-d018641c:~/autodl-tmp# git clone https://github.com/casper-hansen/AutoAWQ.git
Cloning into 'AutoAWQ'...
fatal: unable to access 'https://github.com/casper-hansen/AutoAWQ.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
(base) root@autodl-container-a899408bbc-d018641c:~/autodl-tmp# git clone https://huggingface.co/moka-ai/m3e-base
Cloning into 'm3e-base'...
fatal: unable to access 'https://huggingface.co/moka-ai/m3e-base/': gnutls_handshake() failed: Error in the pull function.

**Comment by VocabVictor** [comment]
同学你按照说明文档，检查过端口是否正常打开了嘛

**Comment by VocabVictor** [comment]
![image](https://github.com/VocabVictor/clash-for-AutoDL/assets/83048106/8c1f2714-a80e-491c-85fe-14c73fc0186a)
我修复了start.sh，按照你的报错测试了一下，没啥问题
