### ISSUE TITLE
到source ./start.sh这一步时启动代理失败

### ISSUE THREAD

**Issue by river-drops** [VocabVictor/clash-for-AutoDL#9]
![1720519375434](https://github.com/VocabVictor/clash-for-AutoDL/assets/59465114/8f8228ba-e555-4c79-b065-02eb8dbe16f1)

QAQ

**Comment by goldenblack2** [comment]
I am same with you,bro

**Comment by VocabVictor** [comment]
我怀疑是大家误删除了logs目录，我在新的代码里面做了更鲁棒的处理
